# baseURL = 'https://reskill-learning.web.app/'
languageCode = 'en-us'
title = 'Reskill Americans'
theme = 'ra-theme'
assetDir = 'assets'

[markup.goldmark.renderer]
# We use nested shortcodes - this is needed to allow them to be nested
# within Markdown.
unsafe= true

[markup.goldmark.parser]
# We don't use the <hN> id's, so they are disabled.  This would be
# needed for fragment links.  So, remove this if we start using them
# or want to support external links to to page fragments.
autoHeadingID = false

[taxonomies]
tag = "tags"

[params]
description = "Tuition-free software development training for underrepresented minorities"
googleAnalytics = "G-Y2KQZFCB07"
email = "info@reskillamericans.org"

[params.socials]
twitter = "ReskillAmerica"
instagram = "reskillamericans"
github = "reskillamericans"
linkedin = "company/reskill-americans"
youtube = "ReskillAmericans"
facebook = "reskillamericans"
