# baseURL = 'https://reskill-learning.web.app/'
languageCode = 'en-US'
title = 'Reskill Americans'
theme = 'ra-theme'
assetDir = 'assets'
summaryLength = 30
disableHugoGeneratorInject = true

[markup.goldmark.renderer]
# We use nested shortcodes - this is needed to allow them to be nested
# within Markdown.
unsafe= true

[taxonomies]
tag = "tags"

[params]
description = "Tuition-free software development training for underrepresented minorities."
googleAnalytics = "G-Y2KQZFCB07"
email = "info@reskillamericans.org"

[params.terms]
cohort = "session"

[params.socials]
twitter = "ReskillAmerica"
instagram = "reskillamericans"
github = "reskillamericans"
linkedin = "company/reskill-americans"
youtube = "ReskillAmericans"
facebook = "reskillamericans"
