# baseURL = 'https://reskill-learning.web.app/'
languageCode = 'en-us'
title = 'Reskill Americans'
theme = 'ra-theme'
assetDir = 'assets'

[taxonomies]
tag = "tags"

[params]
description = "Tuition-free software development training for underrepresented minorities"
googleAnalytics = "G-Y2KQZFCB07"
email = "info@reskillamericans.org"

[params.socials]
twitter = "ReskillAmerica"
instagram = "reskillamericans"
github = "reskillamericans"
linkedin = "company/reskill-americans"
youtube = "ReskillAmericans"
facebook = "reskillamericans"
