#!/bin/bash
#
# build  --- Build website into public directory.

set -e
TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

# Compile TS into a sigle JS file in static/scripts
echo "Bundling TypeScript code..."
bundle

echo "Building Hugo static site..."
rm -rf public
hugo -D
tree public
