#!/bin/bash
#
# build  --- Build website into public directory.

set -e
TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

echo "Clearing public directory ..."
rm -rf public

# Redundant - but get errors from typescript since esbuild does not check.
echo "Checking Typescript errors in site code"
tsc --noEmit

# echo "Checking Typescript errors in functions code"
# cd functions
# tsc --noEmit

cd $PROJ_DIR

# Compile TS into a sigle JS file in static/scripts
echo "Bundling Site TypeScript code ..."
bundle

# TODO: Include theme code in single bundle?
echo "Building Theme's TypeScript code as ESModules ..."
cd $PROJ_DIR/themes/ra-theme
tsc

# Tests are ESModule based - so we need a package.json in a parent directory
# so mocha will run them correctly!  Yuck.
cp $PROJ_DIR/themes/ra-theme/package.json $PROJ_DIR/public/scripts/

cd $PROJ_DIR

echo "Updating video content files from metadata ..."
create-video-content-files.mjs

echo "Building Hugo static site ..."
hugo
tree -L 2 public
