#!/usr/bin/env node
// bundle --- Use ESBuild to bundle code for use in browser.

// ESBuild transpiles TypeScript directly.  We keep the
// tsc build around (and the generated scripts files) for type
// checking.

require('esbuild').buildSync({
    entryPoints: ['src/index.ts'],
    bundle: true,
    format: 'esm',
    treeShaking: true,
    // minify: true,
    sourcemap: true,
    outfile: 'public/scripts/reskill.js',
  })
