#!/bin/bash
#
# run-tests  --- Run Unit Tests

set -e
TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

mocha --ui tdd public/scripts/**/*.test.js

echo Checking html for template errors ...
if grep -l -r --include "*.html" "ZgotmplZ" public; then
    echo -e "\nERROR: Some .html files contain the ZgotmplZ placeholder."
    echo "Possible unsafe content in rendered HTML has been detected."
    echo "Fix before deploying."
    exit 1
fi
