#!/bin/bash
#
# run-tests  --- Run Unit Tests

set -e
TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

mocha --ui tdd public/scripts/**/*.test.js
