#!/bin/bash
#
# test-server --- Run a local web server for testing.

set -e
TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

PORT=5500

cd $PROJ_DIR

if [[ -z "$1" ]]; then
    daemon-command start http-server public --port $PORT
    echo run test-server stop ... to stop.
else
    daemon-command $1 http-server --port $PORT
fi
