#!/bin/bash
#
# test-server --- Run a local web server for testing.

set -e

PORT=5500

cd $PROJ_DIR

if [[ -z "$1" ]]; then
    daemon-command start http-server public --port $PORT
    echo run test-server stop ... to stop.
else
    daemon-command $1 http-server --port $PORT
fi
